### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rayth** [IceYGO/windbot#2]
I tried running the bot in debug mode in VS and it gave me this error:

System.Net.Sockets.SocketException was unhandled
  HResult=-2147467259
  Message=No connection could be made because the target machine actively refused it 127.0.0.1:13254
  Source=System
  ErrorCode=10061
  NativeErrorCode=10061
  StackTrace:
       at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
       at WindBot.Game.Network.GameConnection..ctor(IPAddress address, Int32 port) in c:\Users\Ryan\Downloads\windbot-master\windbot-master\Game\Network\GameConnection.cs:line 29
       at WindBot.Game.GameClient.Start() in c:\Users\Ryan\Downloads\windbot-master\windbot-master\Game\GameClient.cs:line 31
       at WindBot.Program.Run() in c:\Users\Ryan\Downloads\windbot-master\windbot-master\Program.cs:line 40
       at WindBot.Program.Main() in c:\Users\Ryan\Downloads\windbot-master\windbot-master\Program.cs:line 27
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

I didn't modify anything in the code so I don't see why this happened.

**Comment by Zayelion** [comment]
Did you just run it? You have to use a proper command with **ALL** the parameters.

**Comment by Rayth** [comment]
I realised why it didn't work. I forgot to run the server at the same time.
